version: '3'
services:
    admin-service:
        build:
            context: .
            dockerfile: ./docker/admin-service/Dockerfile
        env_file:
            - .env
        volumes:
            - ./admin-service:/var/www/html
        depends_on:
            - database    
        links:
            - database
    database:
        build:
            context: .
            dockerfile: ./docker/database/Dockerfile
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - ./database/data:/var/lib/mysql
            - ./database/init:/docker-entrypoint-initdb.d
    nginx:
        build: ./docker/nginx
        ports:
            # admin-service docker
            - "8081:81"
            # php docker
            - "8080:80"
            # node docker
            - "3000:3000"
        env_file:
            - .env
        volumes:
            - ./server/public:/var/www/html/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        env_file:
            - .env
        volumes:
            - ./server:/var/www/html
    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        restart: always
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        command: sh -c "npm install & npm run dev"