version: '3'
services:
    nginx:
        build: ./docker/nginx
        ports:
            - "8080:80"
        volumes:
            - ./server/public:/var/www/html/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./server:/var/www/html
    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "3000:3000"
        command: sh -c "npm install & npm run dev"